import = [
  "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[window]
padding.x = 10
padding.y = 10
opacity = 0.8
decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 25
