[[session]]
name = "Sesh Settings "
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "cat sesh.toml"

[[session]]
name = "Tmux Settings "
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "cat tmux.conf"

[[session]]
name = "Neovim Settings "
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "Hyprland Settings "
path = "~/.config/hypr"
startup_command = "nvim hyprland.conf"

[[session]]
name = "Ghostty Settings "
path = "~/.config/ghostty"
startup_command = "nvim config"

[[session]]
name = "Zsh Settings "
path = "~/"
startup_command = "nvim ~/.zshrc"

[[session]]
name = "Waybar Settings "
path = "~/.config/waybar"
startup_command = "nvim config"







